[theme]
base = "light"
primaryColor = "#10a37f"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
